version: "3.9"
services:
  nginx:
    image: nginx:1.20.2-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_data:/etc/nginx
      - nginx_log:/var/log/nginx
      - nginx_www:/var/www
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - nginx_network
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
  certbot:
    image: certbot/certbot:arm32v6-v1.27.0
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - nginx_network
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
volumes:
  nginx_data:
    external: true
  nginx_log:
    external: true
  nginx_www:
    external: true
networks:
  nginx_network:
    external: true
